version: "3.9"

networks:
  services:
    external: true
    name: services

services:
  task_service_backend:
    networks:
      - default
      - services
    build:
      context: ../
      dockerfile: ci/Dockerfile
    restart: on-failure
    depends_on:
      db_task:
        condition: service_healthy
    environment:
      POSTGRES_URL: 'postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_task:5432/${POSTGRES_DB}'
    volumes:
      - ../src:/src/app

  db_task:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}", ]
      interval: 5s
      timeout: 5s
      retries: 8
    volumes:
      - task-volume:/var/lib/postgresql/data

volumes:
  task-volume: