version: "3.9"

networks:
  services:
    external: true
    name: services

services:
  user_service_backend:
    networks:
      - default
      - services
    build:
      context: ../
      dockerfile: ci/Dockerfile
    restart: on-failure
    depends_on:
      db_users:
        condition: service_healthy
    environment:
      POSTGRES_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_users:5432/${POSTGRES_DB}'
      POSTGRES_TEST_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_users:5432/test_db'
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_REFRESH_SECRET_KEY: ${JWT_REFRESH_SECRET_KEY}
    volumes:
      - ../src:/src/app

  db_users:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}", ]
      interval: 5s
      timeout: 5s
      retries: 8
    volumes:
      - user-volume:/var/lib/postgresql/data

volumes:
  user-volume: